title: Rebecca Chiaro # your name (or website title) here
logo: "Picture1.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Driven Educator, Math Nerd
  Longtime soccer player, avid traveler, and I have a big sweet tooth!  <br><br>
  <a href="https://www.linkedin.com/in/rebecca-chiaro/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
